[global]
token_header = "Authorization"
token_prefix = "Bearer "

[debug]
address = "0.0.0.0"
token_audience = "https://fulfillment.ross-smart-home.com/"
jwks_url = "https://ross-smart-home.eu.auth0.com/.well-known/jwks.json"
