spring:
  flyway:
    enabled: true
    locations: "classpath:migration"
  datasource:
    url: "jdbc:postgresql://localhost:5432/ross_google_fulfillment"
    username: "postgres"
    password: "postgres"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://ross-smart-home.eu.auth0.com/.well-known/jwks.json"
  cloud:
    gcp:
      project-id: "ross-smart-home"
      credentials:
        location: "classpath:gcp_credentials.json"
        scopes: "https://www.googleapis.com/auth/pubsub"
    function:
      definition: "handleNewGatewayState;handleDeadLetter"
    stream:
      bindings:
        handleNewGatewayState-in-0:
          destination: "projects/ross-smart-home/topics/gateway-state"
        handleDeadLetter-in-0:
          destination: "projects/ross-smart-home/topics/dead-letter"
      gcp:
        pubsub:
          default:
            consumer:
              auto-create-resources: false
          bindings:
            handleNewGatewayState-in-0:
              consumer:
                dead-letter-policy:
                  dead-letter-topic: "projects/ross-smart-home/topics/dead-letter"
                  max-delivery-attempts: 5

gcp:
  project-id: "ross-smart-home"
  region: "europe-west1"
  registry-id: "ross-smart-home"