name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Run tests
        run: |
          ./gradlew test
